### ISSUE TITLE
Unable to perform actions on proto datasets

### ISSUE THREAD

**Issue by f0ster** [scalapb/sparksql-scalapb#61] opened 2020-02-19 01:24 UTC
I have a proto dataframe created with binary data, which has nested nullable structs

```
val ds = binaryRows.map(_.toByteArray).map(MyProto.parseFrom(_))
ds.count()
```

When I try to perform an action that requires serialization, I get the following error:
```
org.apache.spark.SparkException: Task not serializable
  at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:403)
  at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:393)
  at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
  at org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1.apply(RDD.scala:850)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1.apply(RDD.scala:849)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
  at org.apache.spark.rdd.RDD.mapPartitionsWithIndex(RDD.scala:849)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec$$anonfun$doExecute$1.apply(HashAggregateExec.scala:102)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec$$anonfun$doExecute$1.apply(HashAggregateExec.scala:95)
  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.doExecute(HashAggregateExec.scala:95)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:156)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.prepareShuffleDependency(ShuffleExchangeExec.scala:92)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$doExecute$1.apply(ShuffleExchangeExec.scala:128)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$doExecute$1.apply(ShuffleExchangeExec.scala:119)
  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.doExecute(ShuffleExchangeExec.scala:119)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:156)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec$$anonfun$doExecute$1.apply(HashAggregateExec.scala:102)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec$$anonfun$doExecute$1.apply(HashAggregateExec.scala:95)
  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.doExecute(HashAggregateExec.scala:95)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:156)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:283)
  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:332)
  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2836)
  at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2835)
  at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3370)
  at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3369)
  at org.apache.spark.sql.Dataset.count(Dataset.scala:2835)
  ... 47 elided
Caused by: java.io.NotSerializableException: com.google.protobuf.LiteralByteString
Serialization stack:
	- object not serializable (class: com.google.protobuf.LiteralByteString, value: <ByteString@6b5705b5 size=0>)
	- field (class: com.google.protobuf.any.Any, name: value, type: class com.google.protobuf.ByteString)
	- object (class com.google.protobuf.any.Any, Any(,<ByteString@6b5705b5 size=0>))
	- field (class: com.google.protobuf.any.Any$, name: defaultInstance, type: class com.google.protobuf.any.Any)
	- object (class com.google.protobuf.any.Any$, com.google.protobuf.any.Any$@507c70e0)
	- field (class: org.apache.spark.sql.catalyst.expressions.Literal, name: value, type: class java.lang.Object)
....
```

How can I get around this?

**Comment by thesamet** [comment] 2020-02-19 05:20
Hi @f0ster , I originally thought this is related to the usage of `google.protobuf.Any`, but this doesn't seem to be the cause (I added a test that confirms that). My guess is that the sparksql-scalapb implicits don't kick in, so it is failing while trying to serialize with Catalyst. Can you confirm you're using the latest sparksql-scalapb, not having `spark.implicts._` imported in scope, and do have the import `scalapb.spark.Implicits._` ?

If so, it would be great if you can share a minimal example that I can use to reproduce this issue.

**Comment by cinspire93** [comment] 2020-02-29 00:50
Hi @thesamet,  I'm working with Ryan on the same project. This may be a stupid question but I just want to understand how `defaultInstance` is called in the whole serialization stack. We have removed `spark.implicits._` from the scope and kept `scalapb.spark.Implicits._`. However, we are still getting the same error.

**Comment by cinspire93** [comment] 2020-02-29 01:17
Actually let me append that. It looks like whenever we call `parseFrom`, we have to go through `defaultInstance` to `mergeFrom` the input. `Any.defaultInstance` calls on `LiteralByteString` which is not serializable. Since your test uses generated message instead of parse, it might not have to go through same route and hence not raise any errors. I'm pretty new to this so I may very well be wrong. Feel free to point out any mistakes in my logic.

**Comment by thesamet** [comment] 2020-02-29 02:17
`defaultInstance` represents the default instance of a message and as you have found out it is part of the parsing call chain. Essentially, when a message is parsed, we started from the default instance and whenever fields are read from the stream the defaults values are overridden.

I wasn't able to reproduce the error you are seeing by calling `parseFrom` on a message containing an Any in my tests. In my experience, the best way to get to the bottom of those issues is to share an example for me that I can reproduce. Would it be possible for you to add a failing test case AllTypesSpec? You can try using `AT2.AnyTest` as the protobuf.

**Comment by cinspire93** [comment] 2020-03-01 20:52
Sadly I could not recreate the error at all now matter how I manipulate the schema. I'm beginning to suspect it's a dependency hell problem on EMR, and that `scalapb` is calling into EMR's existing protobuf library. EMR's Hadoop library has protobuf pinned at 2.5.0, whose `LiteralByteString` doesn't implement `Serializable` at all, leading to a serialization error on spark.

**Comment by thesamet** [comment] 2020-03-01 21:00
Are you shading com.google.protobuf.* as described here https://scalapb.github.io/sparksql.html#setting-up-your-project ?

**Comment by cinspire93** [comment] 2020-03-01 23:19
Yea I finally got it to work! We are also bringing in some other libraries with proto so I have to shade then merge. But the overall idea remains the same. Thanks for all the help!

**Comment by cinspire93** [comment] 2020-03-01 23:42
Not sure if this question is out of place... After parsing, the array of `MyProto` will be encoded into a data frame. The Any column will be a struct with `type_url` and `value` as its keys. Does scalapb offer any way to unpack the `value` and attach it to the existing data frame?

**Comment by thesamet** [comment] 2020-03-02 01:48
So, if you know that all the `Any`s are a certain type `T`, you can just pass the `value` column through `T.parseFrom` - probably a helper UDF would be needed to make it work. Something like this (haven't tried):

     val parseT = spark.sql.functions.UDF { b: Array[Byte] => T.parseFrom(b) }
     df.withColumn("parsed", parseT($"myany.value"))

If you are accessing the `Any` as a Scala object, you can [use `any.unpack[T]`](url) to get the `T` out of it: https://github.com/scalapb/ScalaPB/blob/66cb51d159053d96d8f407ae0fcdcd1509ac1209/scalapb-runtime/shared/src/main/scala/scalapb/AnyMethods.scala#L13

Since you have indicated that the original problem is resolved, I am closing this issue. Feel free to start a new issue if needed.

**Closed by thesamet** 2020-03-02 01:48 UTC
