### ISSUE TITLE
Scalapb sparksql does not work with Spark 3 (preview)

### ISSUE THREAD

**Issue by SaiKiranBurle** [scalapb/sparksql-scalapb#97] opened 2020-06-06 17:51 UTC
I tried building sparksql-scalapb with spark version `3.0.0-preview2` and it built successfully, but there are runtime errors, mainly missing spark encoders.

I have constructed a minimal example and test here:
https://github.com/SaiKiranBurle/sparksql-scalapb-test

The test can be done using `sbt test`

The specific error that I got from the above test is:
```
[error] java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.<init>(Lorg/apache/spark/sql/types/StructType;ZLscala/collection/Seq;Lorg/apache/spark/sql/catalyst/expressions/Expression;Lscala/reflect/ClassTag;)V
[error]         at frameless.TypedExpressionEncoder$.apply(TypedExpressionEncoder.scala:45)
[error]         at scalapb.spark.Implicits.typedEncoderToEncoder(TypedEncoders.scala:130)
[error]         at scalapb.spark.Implicits.typedEncoderToEncoder$(TypedEncoders.scala:127)
[error]         at scalapb.spark.Implicits$.typedEncoderToEncoder(TypedEncoders.scala:133)
[error]         at ProtoTest.$anonfun$new$1(ProtoTest.scala:26)
[error]         at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[error]         at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[error]         at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[error]         at org.scalatest.Transformer.apply(Transformer.scala:22)
[error]         at org.scalatest.Transformer.apply(Transformer.scala:20)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:189)
[error]         at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[error]         at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[error]         at org.scalatest.funsuite.AnyFunSuite.withFixture(AnyFunSuite.scala:1562)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:187)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:199)
[error]         at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:199)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:181)
[error]         at org.scalatest.funsuite.AnyFunSuite.runTest(AnyFunSuite.scala:1562)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:232)
[error]         at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
[error]         at scala.collection.immutable.List.foreach(List.scala:392)
[error]         at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
[error]         at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
[error]         at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:232)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:231)
[error]         at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1562)
[error]         at org.scalatest.Suite.run(Suite.scala:1112)
[error]         at org.scalatest.Suite.run$(Suite.scala:1094)
[error]         at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1562)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:236)
[error]         at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:236)
[error]         at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:235)
[error]         at org.scalatest.funsuite.AnyFunSuite.run(AnyFunSuite.scala:1562)
[error]         at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:318)
[error]         at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:513)
[error]         at sbt.TestRunner.runTest$1(TestFramework.scala:139)
[error]         at sbt.TestRunner.run(TestFramework.scala:154)
[error]         at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:317)
[error]         at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:277)
[error]         at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)
[error]         at sbt.TestFramework$$anon$3$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:317)
[error]         at sbt.TestFunction.apply(TestFramework.scala:329)
[error]         at sbt.Tests$.$anonfun$toTask$1(Tests.scala:311)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(Transform.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.Execute.work(Execute.scala:290)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
```

**Comment by thesamet** [comment] 2020-06-06 20:27
There is a binary incompatibility between the current version of Frameless (which sparksql-scalapb) is using, and Spark 3. I have filed this ticket upstream (typelevel/frameless#427). At this point we are blocked until the above issue is resolved.

**Comment by paulfryzel** [comment] 2020-09-03 16:16
It looks like both https://github.com/typelevel/frameless/issues/427 and https://github.com/typelevel/frameless/pull/433 have been resolved+merged now. Are there any other blockers?

**Comment by thesamet** [comment] 2020-09-03 16:19
The next step would be to try and update the dependencies and see if this project's test suite passes. Will you be able to look into this and report?

**Comment by paulfryzel** [comment] 2020-09-03 16:28
@thesamet Sure thing. I'll test against their 0.9.0 release. I'll look into it shortly.

**Comment by paulfryzel** [comment] 2020-09-03 18:24
So frameless 0.9.x isn't published anywhere, raised https://github.com/typelevel/frameless/issues/440 for that.

On a build of `frameless-dataset` off master, dropped into a fresh sparksql-scalapb w/ `spark-sql` @ 0.3.0, I'm seeing a series of errors: https://gist.github.com/paulfryzel/1462eb3b2fae5e3abdb80f4ef0b86f75. I'll see what I can step through later on.

**Comment by rsi2m** [comment] 2020-09-29 07:23
@paulfryzel frameless 0.9 seems to be published now.

Did you manage to resolve the aforementioned errors?

**Comment by paulfryzel** [comment] 2020-09-29 20:30
@rsi2m Thanks for the heads up! I've updated [my fork](https://github.com/scalapb/sparksql-scalapb/compare/master...paulfryzel:feature/upgrade-frameless-0.9) accordingly and [reproduced the test output](https://gist.github.com/paulfryzel/0dc55556cb1df6198d05523a6617b761) for review.

Currently, I'm at 20/36 tests passed but haven't had any real time to work on it since. While I may be able to free up some time soon, I'd certainly welcome an additional set of eyes, or I'd be happy to bring others up to speed with my findings.

**Comment by thesamet** [comment] 2020-09-29 23:08
Thanks so much for your help with this @paulfryzel !  I was planning to check out your work on this as well soon and see what's needed to take it to the finishing line.

**Closed** 2020-10-01 00:33 UTC

**Comment by thesamet** [comment] 2020-10-01 00:38
I was able to fix the rest of the tests and we now have Spark 3 fully supported. :tada: 

Big thanks to @paulfryzel for the initial commit. The rest was just working through some obscure change in Spark behavior (possibly a bug?) that has something to do about input null-checks next to `StaticInvoke`. Most code I found does these null checks around `NewInstance` calls, so rewriting how we constructs messages from PMessages did the trick: https://github.com/scalapb/sparksql-scalapb/commit/a468d34f8bef1e3413a8e70372ebcc4cd10865bd#diff-22a116f322ad6eb9e0dbb1a884aa906bR50-R62

**Comment by thesamet** [comment] 2020-10-01 00:43
I released 0.11.0-RC1 - please check it out and report any issues.

**Comment by paulfryzel** [comment] 2020-10-01 00:45
@thesamet Thanks a lot for bringing this all together! Very much appreciated.

Will bring into our development codebases this week and get some feedback.

**Comment by rsi2m** [comment] 2020-10-01 05:38
@paulfryzel @thesamet Thank you guys! Awesome work!
